### PR TITLE
Fix proptype errors

### PR DESCRIPTION
**Pull request by georgegillams**
This relates to this issue: https://github.com/madsleejensen/react-native-transitiongroup/issues/1

### CODE REVIEW

**Comment by madsleejensen** [comment]
Looks good :) but `prop-types` dependency has not been added to `package.json` also could you update the `package.json` peerDependency of "react" and specify the version where React.PropTypes was deprecated.

**Comment by georgegillams** [comment]
https://reactjs.org/docs/typechecking-with-proptypes.html states "React.PropTypes has moved into a different package since React v15.5."

**Comment by madsleejensen** [comment]
Thats great, but could you make it a regular dependency and not a devDependency + update package.json peerDependency react to be react >= 15.5 👍

**Comment by georgegillams** [comment]
Hope that's all good now 😸

**Comment by madsleejensen** [comment]
Great :) but the `prop-types` dependency should be placed in `dependencies` not in `peerDependencies` i can do it when releasing it later today! thanks for the help!

**Comment by georgegillams** [comment]
My bad! All fixed now 👍

**Comment by georgegillams** [comment]
Is there anything preventing this from being merged and released? Plz let me know if I can help at all! 👍 😸

**Comment by madsleejensen** [comment]
Sorry :) its been merged and published now! thanks for your help!

**Comment by georgegillams** [comment]
No worries. Thanks for creating an awesome a component!!

On 7 Nov 2017, 14:29 +0000, Mads Jensen <notifications@github.com>, wrote:

Sorry :) its been merged and published now! thanks for your help!

**Pull request merged**
